using System;
using System.Collections.Generic;
using System.Text;

namespace Serveur.GameServer.Enigma
{
    public enum Category
    {
        MUSIQUE, METIER, EXPRESSION_FAMILIERE, BOISSON, CHOSE_MACHIN_TRUC, TELEVISION, EXPRESSION,
        CUISINE, CELEBRITES, FAUNE_ET_FLORE, LITTERATURE, SPORT, SUR_LA_PLANETE, LIEU_CONNU,
        SEPTIEME_ART, LOISIRS_ET_JEUX, EN_HIVER, BRICOLAGE_ET_JARDINAGE, EN_SOIREE, PERSONNAGE,
        EN_VACANCES
    }
}
